# Generated by Django 4.1.7 on 2023-02-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_product_description_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='D:/School stuffs/P1/images/capacitor.jpg', max_length=100),
        ),
    ]
