# Generated by Django 4.1.7 on 2023-02-26 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_quantity_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
