# Generated by Django 4.1.6 on 2023-02-28 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_category_table_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
