# Generated by Django 4.1.6 on 2023-02-28 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_category_table_alter_product_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
