# Generated by Django 4.1.6 on 2023-02-28 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_product_categories_delete_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
