# Generated by Django 4.1.6 on 2023-02-28 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_category_product_categories'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
