# Generated by Django 4.1.6 on 2023-02-28 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_category_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
