# Generated by Django 4.1.6 on 2023-02-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
