# Generated by Django 4.1.7 on 2023-02-26 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_product_description_product_image_and_more'),
        ('customer', '0002_alter_customer_options'),
        ('cart', '0003_alter_cart_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='product.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('WAIT', 'wait'), ('PAID', 'paid'), ('SHIP', 'shipping'), ('FNSH', 'finished'), ('REFU', 'refunded')], default='WAIT', max_length=4),
        ),
    ]
