# Generated by Django 4.1.6 on 2023-02-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cartproduct_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={},
        ),
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
    ]
